# Generated by Django 5.1.7 on 2025-03-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="production.location",
            ),
            preserve_default=False,
        ),
    ]
