# Generated by Django 5.1.7 on 2025-06-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_item_created_at_item_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-no"]},
        ),
        migrations.AlterModelOptions(
            name="labelperhour",
            options={"ordering": ["-item__no", "location__code"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-no"]},
        ),
        migrations.AlterModelOptions(
            name="output",
            options={"ordering": ["-entry_no"]},
        ),
        migrations.AlterModelOptions(
            name="routing",
            options={"ordering": ["-order__no", "operation_no"]},
        ),
        migrations.AddField(
            model_name="location",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
