# Generated by Django 5.1.7 on 2025-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_alter_item_options_alter_labelperhour_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="unit_of_measure",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
