# Generated by Django 5.1.7 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_item_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="posting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
