# Generated by Django 5.1.7 on 2025-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_output_posting_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="output",
            options={"ordering": ["-posting_date", "-entry_no"]},
        ),
    ]
