# Generated by Django 5.1.7 on 2025-06-21 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_alter_output_options"),
        ("proration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proration",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="proration",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proration",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OutputSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "labels_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=30),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="production.location",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="production.order",
                    ),
                ),
                (
                    "proration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proration.proration",
                    ),
                ),
            ],
            options={
                "ordering": ["-order__no"],
            },
        ),
        migrations.CreateModel(
            name="ProrationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="production.order",
                    ),
                ),
                (
                    "proration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proration.proration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProrationSummaryAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "proration_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proration.prorationsummary",
                    ),
                ),
                (
                    "proration_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="proration.prorationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProrationTypeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=30)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="production.location",
                    ),
                ),
                (
                    "proration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proration.proration",
                    ),
                ),
                (
                    "proration_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="proration.prorationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
