# Generated by Django 5.1.7 on 2025-06-04 08:04

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['no']},
        ),
        migrations.AlterModelOptions(
            name='netchange',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prorationtype',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='netchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prorationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='prorationtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name'),
        ),
    ]
