# Generated by Django 5.1.7 on 2025-06-04 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0002_alter_account_options_alter_netchange_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="prorationtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prorationtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
