# Generated by Django 5.1.7 on 2025-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0003_account_created_at_account_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="active",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=True
            ),
        ),
    ]
