# Generated by Django 5.1.7 on 2025-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0004_alter_account_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-created_at"]},
        ),
    ]
