# Generated by Django 5.1.7 on 2025-06-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0005_alter_account_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["no"]},
        ),
    ]
