# Generated by Django 5.1.7 on 2025-06-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0006_alter_account_options"),
        ("production", "0006_item_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="prorationtype",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="production.location",
            ),
        ),
    ]
