# Generated by Django 5.1.7 on 2025-06-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gl", "0007_prorationtype_location"),
        ("proration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="proration_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proration.prorationtype",
            ),
        ),
        migrations.DeleteModel(
            name="ProrationType",
        ),
    ]
